//2.1.1
Java file for SelectionSort is included.
	
output results: A E E I N O Q S S T U Y 

//2.1.5
when all of the elements in the array are the same.
	
//2.1.9
	
	EASYSHELLSORTQUESTION
E            Q
 A            U
  S            E
   Y            U
    S            S
     H            T
      E            I
       L            O
        L            N
EAESSHELQUSYTION
E   S   Q   T
 A   H   U   I
  E   E   S   O
   S   L   Y   H
EAEHQHELSIOSTUSY
EA...
AE...
AEE...
AEEH...
AEEHQ...
AEEHQH...
AEEHHQ...
AEEHHQE...
AEEEHHQL...
AEEEHHLQS...
AEEEHHLQSI...
AEEEHHILQSO...
AEEEHHILOQSS...
AEEEHHILOQSST...
AEEEHHILOQSSTU...
AEEEHHILOQSSTUS...
AEEEHHULOQSSSTUY...

